pylabel/accounts/models.py
from pylabel import db


class User(db.Model):
    email = db.Column(db.String(128), primary_key=True, unique=True, nullable=False)
    username = db.Column(db.String(128), unique=True, nullable=False)
    password = db.Column(db.String(256))
    authenticated = db.Column(db.Boolean, default=False)

    def is_active(self):
        """True, as all users are active."""
        return True

    def get_id(self):
        """Return the id to satisfy Flask-Login's requirements."""
        return self.email

    def is_authenticated(self):
        """Return True if the user is authenticated."""
        return self.authenticated

    def is_anonymous(self):
        """False, as anonymous users aren't supported."""
        return False

pylabel/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email


class RegisterForm(FlaskForm):
    username = StringField('Email', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])

pylabel/accounts/__init__.py
from pylabel import login_manager


@login_manager.user_loader
def load_user(user_id):
    from pylabel.accounts.models import User
    return User.query.get(user_id)

pylabel/accounts/routes.py
from flask import Blueprint, flash, url_for, redirect, render_template
from flask_login import login_user, login_required, current_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from pylabel.accounts.forms import LoginForm, RegisterForm
from pylabel import db
from pylabel.accounts.models import User

accounts = Blueprint('accounts', __name__, template_folder='templates')


@accounts.route('/')
def index():
    users = User.query.all()
    return render_template('index.html', users=users)


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.email == form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            flash('Logged in successfully.', 'success')
            return redirect(url_for("accounts.index"))

        flash('Invalid login.', 'danger')
        return redirect(url_for("accounts.login"))

    return render_template("login.html", form=form)


@accounts.route("/logout", methods=["GET"])
@login_required
def logout():
    """Logout the current user."""
    logout_user()
    return render_template("logout.html")


@accounts.route("/register", methods=("GET", "POST"))
def register():
    """Register a new user.
    Validates that the username is not already taken. Hashes the
    password for security.
    """
    form = RegisterForm()
    if form.validate_on_submit():
        user = User.query.filter(User.email == form.email.data).first()
        if user:
            flash('Email already taken.', 'info')
            return render_template("register.html", form=form)

        user = User(
            username=form.username.data,
            email=form.email.data,
            password=generate_password_hash(form.password.data)
        )
        db.session.add(user)
        db.session.commit()
        flash('New account created successfully.', 'success')
        return render_template("index.html")

    return render_template("register.html", form=form)

pylabel/accounts/templates/index.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/utils.html" as utils %}

{% block title %} PyLabel Users {% endblock %}

{% block navbar %} {{nav.account_nav.render()}} {% endblock %}


{% block content %}
    {{ utils.flashed_messages() }}

    <table>
    {% for user in users %}
        <tr>
            <td>{{ user.email }}</td>
            <td>{{ user.username }}</td>
        <tr>
    {% endfor %}
   </table>
{% endblock %}

pylabel/accounts/templates/login.html
{% extends "bootstrap/base.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block title %} Login {% endblock %}
{% block styles %} 
{{ super() }}
<link rel="stylesheet"
      href="{{url_for('static', filename='login.css')}}">
{% endblock %}
{% block navbar %} {{nav.account_nav.render()}} {% endblock %}

{% block content %}
    {{ utils.flashed_messages() }}
    <div class="login-form">
    <form action="{{ url_for('accounts.login') }}" method="post">
      <h2 class="text-center">Log in</h2>       
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Username" required="required">
      </div>
      <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" required="required">
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block">Log in</button>
      </div>
      <div class="clearfix">
        <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
        <a href="#" class="pull-right">Forgot Password?</a>
      </div>
    {{ form.csrf_token }}
  </form>
  <p class="text-center"><a href="#">Create an Account</a></p>
</div>
{% endblock %}

pylabel/accounts/templates/logout.html
<html>
    <head>
    </head>
    <body>
        you been logged out son
    </body>
</html>

pylabel/accounts/templates/register.html
{% extends "bootstrap/base.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block title %} Register {% endblock %}

{% block navbar %} {{nav.account_nav.render()}} {% endblock %}

{% block content %}
    {{ utils.flashed_messages() }}
    <form action="{{ url_for('accounts.register') }}" method="post">
        <input type="text" name="username">Username: </input>
        <input type="text" name="email" >Email: </input>
        <input type="password" name="password" >Password: </input>
        <input type="submit" value="Register"/>
        {{ form.csrf_token }}
    </form>
{% endblock %}